# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onversion.proto\"\x16\n\tOperacion\x12\t\n\x01\x61\x18\x01 \x01(\x02\"\x16\n\tResultado\x12\t\n\x01r\x18\x01 \x01(\x02\x32\x66\n\nConversion\x12+\n\x11\x43\x65lsiusFahrenheit\x12\n.Operacion\x1a\n.Resultado\x12+\n\x11\x46\x61hrenheitCelsius\x12\n.Operacion\x1a\n.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACION']._serialized_start=20
  _globals['_OPERACION']._serialized_end=42
  _globals['_RESULTADO']._serialized_start=44
  _globals['_RESULTADO']._serialized_end=66
  _globals['_CONVERSION']._serialized_start=68
  _globals['_CONVERSION']._serialized_end=170
# @@protoc_insertion_point(module_scope)
