# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conversion_pb2 as conversion__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conversion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CelsiusFahrenheit = channel.unary_unary(
                '/Conversion/CelsiusFahrenheit',
                request_serializer=conversion__pb2.Operacion.SerializeToString,
                response_deserializer=conversion__pb2.Resultado.FromString,
                _registered_method=True)
        self.FahrenheitCelsius = channel.unary_unary(
                '/Conversion/FahrenheitCelsius',
                request_serializer=conversion__pb2.Operacion.SerializeToString,
                response_deserializer=conversion__pb2.Resultado.FromString,
                _registered_method=True)


class ConversionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CelsiusFahrenheit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FahrenheitCelsius(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CelsiusFahrenheit': grpc.unary_unary_rpc_method_handler(
                    servicer.CelsiusFahrenheit,
                    request_deserializer=conversion__pb2.Operacion.FromString,
                    response_serializer=conversion__pb2.Resultado.SerializeToString,
            ),
            'FahrenheitCelsius': grpc.unary_unary_rpc_method_handler(
                    servicer.FahrenheitCelsius,
                    request_deserializer=conversion__pb2.Operacion.FromString,
                    response_serializer=conversion__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Conversion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Conversion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Conversion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CelsiusFahrenheit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Conversion/CelsiusFahrenheit',
            conversion__pb2.Operacion.SerializeToString,
            conversion__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FahrenheitCelsius(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Conversion/FahrenheitCelsius',
            conversion__pb2.Operacion.SerializeToString,
            conversion__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
